server:
  port: 8001

spring:
  application:
    name: itest-config

  rabbitmq:
    host: 176.10.10.233
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

msg: this is local config

