server:
  port: 8000

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/rocye/SpringcloudConfig/
          searchPaths: springcloudstudy
#         username: ***
#         password: ***
  rabbitmq:
    host: 176.10.10.233
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#新版本新的配置方法: /actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: ["bus-refresh"]

